name: Deploy Web

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.5

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build distributions files
        run: ./gradlew jsBrowserProductionWebpack

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/distributions'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1